version: '3.8'

services:
  mysql:
    container_name: mysql-devsu
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3305:8080
    environment:
      ADMINER_DEFAULT_USERNAME: root
      ADMINER_DEFAULT_PASSWORD: password

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  consul:
    image: consul:1.15.4
    restart: always
    ports:
      - "8500:8500"

  gateway:
    # Configura tu contenedor para el gateway aquí
    # Por ejemplo, puedes usar una imagen de nginx o spring cloud gateway
    # Consulta la documentación oficial de la herramienta que elijas para obtener instrucciones detalladas
    image: nginx:latest
    restart: always
    ports:
      - "80:80"

  cliente-service:
    container_name: cliente_devsu
    build:
      context: ./cliente
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "${CLIENTE_SERVICE_PORT}:${CLIENTE_SERVICE_PORT}"
    depends_on:
      - mysql


  movimiento-service:
    container_name: movimiento_devsu
    build:
      context: ./movimiento
      dockerfile: Dockerfile
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - .env
    ports:
      - "${MOVIMIENTO_SERVICE_PORT}:${MOVIMIENTO_SERVICE_PORT}"
      - 5005:5005
    depends_on:
      - mysql
      - cliente-service

volumes:
  mysql_data:


