application:
  name: gateway-service

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: PA7yzvF7OYykVl7p3Us6Hrbsd16JVGTQ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/auth/realms/devsu
  main:
    web-application-type: reactive
  boot:
    admin:
      client:
        url: "http://localhost:8090"
  application:
    name: gateway-service
  cloud:
    consul:
      config:
        enabled: true
      host: localhost
      port: 8500
    gateway:
      discovery:
        instanceId: ${application.name}:${random.value}
        locator:
          enabled: true
      routes:
        - id: clientes-resource
          uri: lb://cliente-service/clientes/
          predicates:
            - Path=/clientes/**
        - id: movimiento-resource
          uri: lb://movimiento-service/movimientos/
          predicates:
            - Path=/movimientos/**
        - id: cuenta-resource
          uri: lb://movimiento-service/cuentas/
          predicates:
            - Path=/cuentas/**

server:
  port: 8080

logging:
  level:
    org.springframework.core.codec.StringDecoder: TRACE
    org:
      springframework:
        security: DEBUG
        keycloak: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true


