application:
  server:
    port: ${MOVIMIENTO_SERVICE_PORT}
server:
  port: ${application.server.port}
spring:
  boot:
    admin:
      client:
        url: ${ADMINER_SERVICE_HOST}:${ADMINER_SERVICE_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      group-id: my-group
  cloud:
    consul:
      discovery:
        health-check-interval: 90s
      host: ${CONSUL_HOST}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/devsu?allowPublicKeyRetrieval=false&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: INFO
    com:
      devsu:
        movimiento: INFO
    io:
      springcloud:
        consul: INFO


