name: Docker Image CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build the Docker image in the movimiento directory
      run: |
        cd movimiento
        mvn clean package
        docker build . --file ./Dockerfile --tag rdsantopietro/movimiento:latest

    - name: Push image to Docker Hub
      run: docker push rdsantopietro/movimiento:latest

