name: Docker Image CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build the Docker image in the movimiento directory
      run: |
        cd movimiento
        mvn clean package
        docker build . --file ./Dockerfile --tag rdsantopietro/movimiento
  
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
         username: ${{ vars.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Build and push Docker image
      run: docker push rdsantopietro/movimiento:latest
  
  
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_EC2_AWS_PRIVATE_KEY }}

      - name: Add remote host to known_hosts
        run: ssh-keyscan -H ec2-107-21-189-154.compute-1.amazonaws.com >> ~/.ssh/known_hosts


      - name: SSH into the host and download Docker image
        run: |
          ssh ubuntu@ec2-107-21-189-154.compute-1.amazonaws.com "docker pull movimiento"
    
         
      
          
       
