name: Docker Image CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:

  build:

    runs-on: ubuntu-latest
   

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDKs
      run: |
        echo "variable: ${{ env.DOCKER_USER }}"

        
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build the Docker image in the movimiento directory
      run: |
        echo "variable: ${{ env.DOCKER_USER }}"
        cd movimiento
        mvn clean package
        docker build . --file ./Dockerfile --tag rdsantopietro/movimiento:latest
  
  push:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: Push image to Docker Hub
      run: |
        echo $DOCKER_USER
        echo $DOCKER_PASSWORD
        docker login --username DOCKER_USER --password DOCKER_PASSWORD
        run: docker push rdsantopietro/movimiento:latest
