name: Docker Image CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - uses: actions/checkout@v3
    - name: Build the Docker image in the movimiento directory
      run: |
        cd movimiento
        mvn clean package
        docker build . --file ./Dockerfile --tag rdsantopietro/movimiento:latest

  push_image:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - uses: actions/checkout@v3
    - name: Push image to Docker Hub
      run: docker push rdsantopietro/movimiento:latest
